apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkusrobotshop-package
  labels:
    app: quarkusrobotshop-package
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replica_count.package }}
  selector:
    matchLabels:
      app: quarkusrobotshop-package
  template:
    metadata:
      name: quarkusrobotshop-package-deployment
      labels:
        app:  quarkusrobotshop-package
        release: {{ .Release.Name }}
        app.kubernetes.io/component: quarkusrobotshop-package
        app.kubernetes.io/instance: quarkusrobotshop-package
        app.kubernetes.io/part-of: quarkus-robot
        quarkus-robot: ""
        app.openshift.io/runtime-namespace: {{ .Values.projectnamespace }}
    spec:
      containers:
        - name: quarkusrobotshop-package
          image: quay.io/quarkusrobotshop/quarkusrobotshop-package:{{ .Values.version.package }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8778
              protocol: TCP
            - containerPort: 9779
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: {{ .Values.kafka_cluster_name }}-kafka-bootstrap:9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkusrobotshop-inventory
  labels:
    app: quarkusrobotshop-inventory
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replica_count.inventory }}
  selector:
    matchLabels:
      app: quarkusrobotshop-inventory
  template:
    metadata:
      name: quarkusrobotshop-inventory-deployment
      labels:
        app:  quarkusrobotshop-inventory
        release: {{ .Release.Name }}
        app.kubernetes.io/component: quarkusrobotshop-inventory
        app.kubernetes.io/instance: quarkusrobotshop-inventory
        app.kubernetes.io/part-of: quarkus-robot
        quarkus-robot: ""
        app.openshift.io/runtime-namespace: {{ .Values.projectnamespace }}
    spec:
      containers:
        - name: quarkusrobotshop-inventory
          image: quay.io/quarkusrobotshop/quarkusrobotshop-inventory:{{ .Values.version.inventory }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8778
              protocol: TCP
            - containerPort: 9779
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: {{ .Values.kafka_cluster_name }}-kafka-bootstrap:9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkusrobotshop-counter
  labels:
    app: quarkusrobotshop-counter
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replica_count.counter }}
  selector:
    matchLabels:
      app: quarkusrobotshop-counter
  template:
    metadata:
      name: quarkusrobotshop-counter-deployment
      labels:
        app:  quarkusrobotshop-counter
        release: {{ .Release.Name }}
        app.kubernetes.io/component: quarkusrobotshop-counter
        app.kubernetes.io/instance: quarkusrobotshop-counter
        app.kubernetes.io/part-of: quarkus-robot
        quarkus-robot: ""
        app.openshift.io/runtime-namespace: {{ .Values.projectnamespace }}
    spec:
      containers:
        - name: quarkusrobotshop-counter
          image: quay.io/quarkusrobotshop/quarkusrobotshop-counter:{{ .Values.version.counter }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: 'robot-cluster-kafka-bootstrap:9092'
            - name: PGSQL_URL
              value: {{ .Values.pgsql_url }}
            - name: PGSQL_USER
              value: {{ .Values.pgsql_username }}
            - name: PGSQL_PASS
              value: {{ .Values.pgsql_password }}
            - name: LOG_SQL
              value: 'true'
            - name: QUARKUS_LOG_LEVEL
              value: {{ .Values.quarkus_log_level }}
            - name: QUARKUSrobotSHOP_LOG_LEVEL
              value: {{ .Values.quarkusrobotshop_log_level }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkusrobotshop-customermocker
  labels:
    app: quarkusrobotshop-customermocker
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replica_count.customermocker }}
  selector:
    matchLabels:
      app: quarkusrobotshop-customermocker
  template:
    metadata:
      name: quarkusrobotshop-customermocker-deployment
      labels:
        app:  quarkusrobotshop-customermocker
        release: {{ .Release.Name }}
        app.kubernetes.io/component: quarkusrobotshop-customermocker
        app.kubernetes.io/instance: quarkusrobotshop-customermocker
        app.kubernetes.io/part-of: quarkus-robot
        quarkus-robot: ""
        app.openshift.io/runtime-namespace: {{ .Values.projectnamespace }}
    spec:
      containers:
        - name: quarkusrobotshop-customermocker
          image: quay.io/quarkusrobotshop/quarkusrobotshop-customermocker:{{ .Values.version.customermocker }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: REST_URL
              value: http://quarkusrobotshop-web-{{ .Values.projectnamespace }}.apps.{{ .Values.domain }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkusrobotshop-customize
  labels:
    app: quarkusrobotshop-customize
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replica_count.customize }}
  selector:
    matchLabels:
      app: quarkusrobotshop-customize
  template:
    metadata:
      name: quarkusrobotshop-customize-deployment
      labels:
        app:  quarkusrobotshop-customize
        release: {{ .Release.Name }}
        app.kubernetes.io/component: quarkusrobotshop-customize
        app.kubernetes.io/instance: quarkusrobotshop-customize
        app.kubernetes.io/part-of: quarkus-robot
        quarkus-robot: ""
        app.openshift.io/runtime-namespace: {{ .Values.projectnamespace }}
    spec:
      containers:
        - name: quarkusrobotshop-customize
          image: quay.io/quarkusrobotshop/quarkusrobotshop-customize:{{ .Values.version.customize }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: {{ .Values.kafka_cluster_name }}-kafka-bootstrap:9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkusrobotshop-customerloyalty
  labels:
    app: quarkusrobotshop-customerloyalty
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replica_count.customerloyalty }}
  selector:
    matchLabels:
      app: quarkusrobotshop-customerloyalty
  template:
    metadata:
      name: quarkusrobotshop-customerloyalty-deployment
      labels:
        app:  quarkusrobotshop-customerloyalty
        release: {{ .Release.Name }}
        app.kubernetes.io/component: quarkusrobotshop-customerloyalty
        app.kubernetes.io/instance: quarkusrobotshop-customerloyalty
        app.kubernetes.io/part-of: quarkus-robot
        quarkus-robot: ""
        app.openshift.io/runtime-namespace: {{ .Values.projectnamespace }}
    spec:
      containers:
        - name: quarkusrobotshop-customerloyalty
          image: quay.io/quarkusrobotshop/quarkusrobotshop-customerloyalty:{{ .Values.version.customerloyalty }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: {{ .Values.kafka_cluster_name }}-kafka-bootstrap:9092
            - name: QUARKUS_LOG_LEVEL
              value: {{ .Values.quarkus_log_level }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkuscoffeshop-web
  labels:
    app: quarkusrobotshop-web
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replica_count.web }}
  selector:
    matchLabels:
      app: quarkusrobotshop-web
  template:
    metadata:
      name: quarkusrobotshop-web
      labels:
        app: quarkusrobotshop-web
        release: {{ .Release.Name }}
        app.kubernetes.io/component: quarkusrobotshop-web
        app.kubernetes.io/instance: quarkusrobotshop-web
        app.kubernetes.io/part-of: quarkusrobotshop
        quarkus-robot: ""
        app.openshift.io/runtime-namespace: {{ .Values.projectnamespace }}
    spec:
      containers:
        - name: quarkusrobotshop-web
          image: quay.io/quarkusrobotshop/quarkusrobotshop-web:{{ .Values.version.web }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka_cluster_name }}-kafka-bootstrap:9092
            - name: REST_URL
              value: http://quarkusrobotshop-web-{{ .Values.projectnamespace }}.apps.{{ .Values.domain }}
            - name: STREAM_URL
              value:  http://quarkusrobotshop-web-{{ .Values.projectnamespace }}.apps.{{ .Values.domain }}/dashboard/stream
            - name: LOYALTY_STREAM_URL
              value: http://quarkusrobotshop-web-{{ .Values.projectnamespace }}.apps.{{ .Values.domain }}/dashboard/loyaltystream
            - name: CORS_ORIGINS
              value: http://quarkusrobotshop-web-{{ .Values.projectnamespace }}.apps.{{ .Values.domain }}
            - name: STORE_ID
              value: {{ .Values.storeid }}
