apiVersion: v1
kind: Service
metadata:
  name: quarkusrobotshop-homerobot
  labels:
    app:  quarkusrobotshop-homerobot
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    app:  quarkusrobotshop-homerobot
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    - name: 9779-tcp
      port: 9779
      protocol: TCP
      targetPort: 9779
---
apiVersion: v1
kind: Service
metadata:
  name: quarkusrobotshop-core
  labels:
    app: quarkusrobotshop-core
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: quarkusrobotshop-core
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quarkusrobotshop-customermocker
  labels:
    app: quarkusrobotshop-customermocker
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: quarkusrobotshop-customermocker
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quarkusrobotshop-prorobot
  labels:
    app: quarkusrobotshop-prorobot
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: quarkusrobotshop-prorobot
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quarkusrobotshop-inventory
  labels:
    app: quarkusrobotshop-inventory
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: quarkusrobotshop-inventory
  type: ClusterIP
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quarkusrobotshop-customerloyalty
  labels:
    app: quarkusrobotshop-customerloyalty
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: quarkusrobotshop-customerloyalty
  type: ClusterIP
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quarkusrobotshop-web
  labels:
    app: quarkusrobotshop-web
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: quarkusrobotshop-web
  type: ClusterIP
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080